version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: baking
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge