name: CI/CD Banking service application

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: maven

      - name: Build and Test
        run: |
          ./mvnw clean install
        working-directory: ./ 

      - name: Create Docker image
        run: |
          docker build -t banking-service:${{ github.sha }} .
        working-directory: ./ 

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push sua-imagem-spring-boot:${{ github.sha }}
      - name: Create Pull Request to Develop
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          branch: develop
          base: develop
